kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
#name: cilium-up-and-running-cluster
nodes:
- role: control-plane
- role: worker
- role: worker
networking:
  disableDefaultCNI: true
  kubeProxy: none