autoDirectNodeRoutes: true
bpf:
  masquerade: true
cluster:
  name: kind-kind
ipam:
  mode: kubernetes
ipv4NativeRoutingCIDR: 10.0.0.0/8
kubeProxyReplacement: true
loadBalancer:
  serviceTopology: true
operator:
  replicas: 1
routingMode: native