kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  ServiceTrafficDistribution: true
nodes:
- role: control-plane
- role: worker
  labels:
    topology.kubernetes.io/zone: zone-a
- role: worker
  labels:
    topology.kubernetes.io/zone: zone-b
networking:
  disableDefaultCNI: true
  kubeProxyMode: none