apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cuar
  region: eu-west-1

managedNodeGroups:
- name: ng-1
  desiredCapacity: 2
  privateNetworking: true
  taints:
   - key: "node.cilium.io/agent-not-ready"
     value: "true"
     effect: "NoExecute"
