kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.33.0
- role: worker
  image: kindest/node:v1.33.0
- role: worker
  image: kindest/node:v1.33.0
networking:
  ipFamily: ipv6
  disableDefaultCNI: true
  podSubnet: "2001:db8:10:244::/48"
  serviceSubnet: "2001:db8:10:96::/112"
