apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "http-visibility"
  namespace: l7-visibility
spec:
  endpointSelector: {}
  egress:
  - toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      rules:
        http:
        - {}
  - toEntities:
    - world
