apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: internal-ca-bundle
spec:
  sources:
    - secret:
        name: root
        key: "ca.crt"
  target:
    configMap:
      key: "ca.crt"
