kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.33.0
- role: worker
  image: kindest/node:v1.33.0
  labels:
    topology.kubernetes.io/zone: zone-a
- role: worker
  image: kindest/node:v1.33.0
  labels:
    topology.kubernetes.io/zone: zone-a
- role: worker
  image: kindest/node:v1.33.0
  labels:
    topology.kubernetes.io/zone: zone-b
- role: worker
  image: kindest/node:v1.33.0
  labels:
    topology.kubernetes.io/zone: zone-b
networking:
  disableDefaultCNI: true
  kubeProxyMode: none