apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: anti-lockout
spec:
  nodeSelector: {}
  enableDefaultDeny:
    ingress: false
    egress: false
  ingress:
    - toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
            - port: "22"
              protocol: TCP
    - fromEntities:
        - cluster
  egress:
    - toEntities:
        - cluster
