kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
nodes:
- role: control-plane
  image: kindest/node:v1.33.0
# Compute nodes
- role: worker
  image: kindest/node:v1.33.0
- role: worker
  image: kindest/node:v1.33.0
# Egress nodes
- role: worker
  image: kindest/node:v1.33.0
  labels:
    egress-gw: true
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "egress-gw=true"
        register-with-taints: "egress-gw:NoSchedule"
- role: worker
  image: kindest/node:v1.33.0
  labels:
    egress-gw: true
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "egress-gw=true"
        register-with-taints: "egress-gw:NoSchedule"