apiVersion: v1
kind: Service
metadata:
  name: whatsmyip-nodeport
spec:
  type: NodePort
  selector:
    app: whatsmyip
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      nodePort: 30080