apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: public-ca-bundle
spec:
  sources:
    - useDefaultCAs: true
  target:
    secret:
      key: "ca.crt"
    namespaceSelector:
      matchLabels:
        secrets-namespace: "true"
