apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-worker
  template:
    metadata:
      labels:
        app: pod-worker
    spec:
      containers:
      - name: netshoot
        image: nicolaka/netshoot:latest
        command: ["sleep", "infinite"]
